import { GET_ALL_FRIENDS, ENTER_ROOM, NEW_MESSAGE, BROCAST_MESSAGE, PULL_MORE, NEW_BACTH_MESSAGES } from '../../common/SocketConstants';

// export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
// export const USER_INFO = 'USER_INFO';
// export const SIGN_OUT = 'SIGN_OUT';
//
// export GET_ALL_FRIENDS;

const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
const USER_INFO = 'USER_INFO';
const SIGN_OUT = 'SIGN_OUT';
const NEW_SELF_MESSAGE = 'NEW_SELF_MESSAGE';


module.exports = {
    IS_AUTHENTICATED,
    USER_INFO,
    SIGN_OUT,
    GET_ALL_FRIENDS,
    ENTER_ROOM,
    NEW_MESSAGE,
    NEW_SELF_MESSAGE,
    BROCAST_MESSAGE,
    PULL_MORE,
    NEW_BACTH_MESSAGES
}
