const CHANNEL_NAME = 'ASAPP';
const CONNECTION = 'connection';
const ENTER_ROOM = 'SERVER/ENTER_ROOM';
const LEAVE_ROOM = 'SERVER/LEAVE_ROOM';
const BROCAST_MESSAGE = 'SERVER/BROCAST_MESSAGE';
const NEW_MESSAGE = 'SERVER/NEW_MESSAGE';
const PULL_MORE = 'SERVER/PULL_MORE';
const NEW_BACTH_MESSAGES = 'SERVER/NEW_BACTH_MESSAGES';
const CHAT_PATH = '/api/chat';
const SERVER_SOCEKT_ACTION_PATH = 'SERVER/';
const SERVER_ACTION = 'action';
const BATCH_MESSAGE_SIZE = 2;


const GET_ALL_FRIENDS = 'SERVER/GET_ALL_FRIENDS';

module.exports = {
    CHANNEL_NAME: CHANNEL_NAME,
    CONNECTION: CONNECTION,
    ENTER_ROOM: ENTER_ROOM,
    NEW_MESSAGE: NEW_MESSAGE,
    PULL_MORE: PULL_MORE,
    CHAT_PATH: CHAT_PATH,
    SERVER_SOCEKT_ACTION_PATH: SERVER_SOCEKT_ACTION_PATH,
    SERVER_ACTION: SERVER_ACTION,
    GET_ALL_FRIENDS: GET_ALL_FRIENDS,
    BROCAST_MESSAGE: BROCAST_MESSAGE,
    BATCH_MESSAGE_SIZE: BATCH_MESSAGE_SIZE,
    NEW_BACTH_MESSAGES: NEW_BACTH_MESSAGES
}
